### ISSUE TITLE
Duplicate of existing Mix plugin?

### ISSUE THREAD

**Issue by colourgarden** [leowebguy/mix-manifest#1]
Hi @leowebguy,

Could you outline the differences between your plugin and the existing, well-established Mix plugin - https://github.com/mister-bk/craft-plugin-mix

The plugins appear to cover the same functionality so it seems unnecessary to have duplicates in the Craft plugin store. If your plugin introduces something new then could it be contributed to the existing plugin? Or maybe contact the plugin author to take over their project.

Thanks!

**Comment by leowebguy** [comment]
mine is simpler... no settings, no variables, just what I need.
