### ISSUE TITLE
Sitewide Error on Mix 1.0.3

### ISSUE THREAD

**Issue by cherrykoda** [leowebguy/mix-manifest#5]
Massive sitewide error with version 1.0.3 -- I was able to downgrade back to 1.0.2 to avoid the issue for now.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/3789834/228114446-81d9266f-1c7f-4ae6-9210-b3f458f6dc00.png">

Craft Pro 3.8.5
Mix 1.0.3
PHP 8.1.13
MariaDB 10.10.2

**Comment by cherrykoda** [comment]
I'm now getting this with any Craft website that I run a composer update on. I've hard set to v1.0.2 for now. Including those on PHP 8.2

**Comment by dodgycoffee** [comment]
Can confirm. Tested locally on a previously working repo with php 8.2. Rolling back a version removed the error.

**Comment by leowebguy** [comment]
Could swear I tagged 1.0.3 for craft 4 only... for now I've deleted the version I'll fix it later.
